// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitFlowAPI.Data;

#nullable disable

namespace VisitFlowAPI.Migrations
{
    [DbContext(typeof(VisitFlowDbContext))]
    [Migration("20260330184257_SupplierDocumentsCompanyFiles")]
    partial class SupplierDocumentsCompanyFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitFlowAPI.Models.Approved", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredApproversCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("Approveds");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.BlacklistRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("BlacklistRequests");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ComplianceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleOrFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<bool>("ValidatedByAI")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("TypeOfWorkId");

                    b.ToTable("ComplianceItems", t =>
                        {
                            t.HasCheckConstraint("CK_ComplianceItem_Owner", "([PersonnelId] IS NOT NULL AND [TypeOfWorkId] IS NULL) OR ([PersonnelId] IS NULL AND [TypeOfWorkId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ElementOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementTypeId");

                    b.ToTable("ElementOptions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ElementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElementTypes");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirePermitDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSEComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeightPermitDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HseFormDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHSEValidated")
                        .HasColumnType("bit");

                    b.Property<int>("MinPersonnel")
                        .HasColumnType("int");

                    b.Property<int>("MinZone")
                        .HasColumnType("int");

                    b.Property<string>("Ppi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeOfWorkId");

                    b.HasIndex("VisitId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementTypeId");

                    b.HasIndex("FormId");

                    b.HasIndex("InterventionId");

                    b.ToTable("InterventionElements");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPersonnel", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InterventionId", "PersonnelId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("InterventionPersonnels");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPlant", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("InterventionId", "PlantId");

                    b.HasIndex("PlantId");

                    b.ToTable("InterventionPlants");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionZone", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("InterventionId", "ZoneId");

                    b.HasIndex("ZoneId");

                    b.ToTable("InterventionZones");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cin")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeOfWorkId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.PersonnelTraining", b =>
                {
                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date");

                    b.HasKey("PersonnelId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("PersonnelTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.SafetyMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("SafetyMeasures");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.SupplierDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierDocuments");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresInsurance")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TypeOfWorks");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkInsurance", b =>
                {
                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("TypeOfWorkId", "InsuranceId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("TypeOfWorkInsurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkTraining", b =>
                {
                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("TypeOfWorkId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Validation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidatedByRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("Validations");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Approved", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("Approved")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.BlacklistRequest", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("BlacklistRequests")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.User", "ReviewedByUser")
                        .WithMany("ReviewedBlacklistRequests")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Personnel");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ComplianceItem", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("ComplianceItems")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("ComplianceItems")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Personnel");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Document", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithOne("Document")
                        .HasForeignKey("VisitFlowAPI.Models.Document", "InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ElementOption", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.ElementType", "ElementType")
                        .WithMany("ElementOptions")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementType");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Form", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Document", "Document")
                        .WithMany("Forms")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("Insurances")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.User", "CreatedByUser")
                        .WithMany("CreatedInterventions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Supplier", "Supplier")
                        .WithMany("Interventions")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("Interventions")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Visit", "Visit")
                        .WithMany("Interventions")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Supplier");

                    b.Navigation("TypeOfWork");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionElement", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.ElementType", "ElementType")
                        .WithMany("InterventionElements")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Form", "Form")
                        .WithMany("InterventionElements")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("InterventionElements")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementType");

                    b.Navigation("Form");

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPersonnel", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("InterventionPersonnels")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("InterventionPersonnels")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPlant", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("InterventionPlants")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Plant", "Plant")
                        .WithMany("InterventionPlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionZone", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("InterventionZones")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Zone", "Zone")
                        .WithMany("InterventionZones")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Supplier", "Supplier")
                        .WithMany("Personnel")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("Personnels")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supplier");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.PersonnelTraining", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("PersonnelTrainings")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Training", "Training")
                        .WithMany("PersonnelTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.SafetyMeasure", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("SafetyMeasures")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Session", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.SupplierDocument", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Supplier", "Supplier")
                        .WithMany("SupplierDocuments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkInsurance", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Insurance", "Insurance")
                        .WithMany("TypeOfWorkInsurances")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("TypeOfWorkInsurances")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkTraining", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Training", "Training")
                        .WithMany("TypeOfWorkTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("TypeOfWorkTrainings")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Validation", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany()
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Visit", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Document", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.ElementType", b =>
                {
                    b.Navigation("ElementOptions");

                    b.Navigation("InterventionElements");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Form", b =>
                {
                    b.Navigation("InterventionElements");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.Navigation("TypeOfWorkInsurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.Navigation("Approved");

                    b.Navigation("Document");

                    b.Navigation("InterventionElements");

                    b.Navigation("InterventionPersonnels");

                    b.Navigation("InterventionPlants");

                    b.Navigation("InterventionZones");

                    b.Navigation("SafetyMeasures");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.Navigation("BlacklistRequests");

                    b.Navigation("ComplianceItems");

                    b.Navigation("Insurances");

                    b.Navigation("InterventionPersonnels");

                    b.Navigation("PersonnelTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Plant", b =>
                {
                    b.Navigation("InterventionPlants");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Supplier", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Personnel");

                    b.Navigation("SupplierDocuments");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Training", b =>
                {
                    b.Navigation("PersonnelTrainings");

                    b.Navigation("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWork", b =>
                {
                    b.Navigation("ComplianceItems");

                    b.Navigation("Interventions");

                    b.Navigation("Personnels");

                    b.Navigation("TypeOfWorkInsurances");

                    b.Navigation("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.User", b =>
                {
                    b.Navigation("CreatedInterventions");

                    b.Navigation("ReviewedBlacklistRequests");

                    b.Navigation("Sessions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Visit", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Zone", b =>
                {
                    b.Navigation("InterventionZones");
                });
#pragma warning restore 612, 618
        }
    }
}
