// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitFlowAPI.Data;

#nullable disable

namespace VisitFlowAPI.Migrations
{
    [DbContext(typeof(VisitFlowDbContext))]
    [Migration("20260324132411_NormalizeUserRolesToFourActors")]
    partial class NormalizeUserRolesToFourActors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitFlowAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HSEComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHSEValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeOfWorkId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPersonnel", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InterventionId", "PersonnelId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("InterventionPersonnels");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cin")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.PersonnelTraining", b =>
                {
                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date");

                    b.HasKey("PersonnelId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("PersonnelTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresInsurance")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TypeOfWorks");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkInsurance", b =>
                {
                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("TypeOfWorkId", "InsuranceId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("TypeOfWorkInsurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkTraining", b =>
                {
                    b.Property<int>("TypeOfWorkId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("TypeOfWorkId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Document", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("Documents")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("Insurances")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.User", "CreatedByUser")
                        .WithMany("CreatedInterventions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Supplier", "Supplier")
                        .WithMany("Interventions")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("Interventions")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Zone", "Zone")
                        .WithMany("Interventions")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Supplier");

                    b.Navigation("TypeOfWork");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.InterventionPersonnel", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Intervention", "Intervention")
                        .WithMany("InterventionPersonnels")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("InterventionPersonnels")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Supplier", "Supplier")
                        .WithMany("Personnel")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.PersonnelTraining", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Personnel", "Personnel")
                        .WithMany("PersonnelTrainings")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.Training", "Training")
                        .WithMany("PersonnelTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkInsurance", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Insurance", "Insurance")
                        .WithMany("TypeOfWorkInsurances")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("TypeOfWorkInsurances")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWorkTraining", b =>
                {
                    b.HasOne("VisitFlowAPI.Models.Training", "Training")
                        .WithMany("TypeOfWorkTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitFlowAPI.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("TypeOfWorkTrainings")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Insurance", b =>
                {
                    b.Navigation("TypeOfWorkInsurances");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Intervention", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("InterventionPersonnels");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Personnel", b =>
                {
                    b.Navigation("Insurances");

                    b.Navigation("InterventionPersonnels");

                    b.Navigation("PersonnelTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Supplier", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Training", b =>
                {
                    b.Navigation("PersonnelTrainings");

                    b.Navigation("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.TypeOfWork", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("TypeOfWorkInsurances");

                    b.Navigation("TypeOfWorkTrainings");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.User", b =>
                {
                    b.Navigation("CreatedInterventions");
                });

            modelBuilder.Entity("VisitFlowAPI.Models.Zone", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
